# -*- coding: utf-8 -*-
"""Langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tiv0ZHWRPMeXZruclk4gCXPWslQ76thS
"""

pip install langchain openai

pip install langchain-community

from langchain_community.document_loaders import PyPDFLoader
from langchain_openai.embeddings import OpenAIEmbeddings
from langchain.vectorstores import FAISS
from langchain.chains import RetrievalQA
from langchain_openai.chat_models import ChatOpenAI

loader = PyPDFLoader("/content/David Lay, Steven Lay, Judi McDonald, Linear Algebra and Its Applications, 2021.pdf")
documents = loader.load()

import os
os.environ["OPENAI_API_KEY"] = ""
embeddings = OpenAIEmbeddings()

vectorstores = FAISS.from_documents(documents, embeddings)

