# -*- coding: utf-8 -*-
"""Learning_ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TBu-X0cRTvuaZ6Vg1kG6Zsqm4dJw5MoS
"""

pip install langchain google-generativeai langchain-google-genai

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_core.messages import AIMessage, HumanMessage
from langchain_core.chat_history import InMemoryChatMessageHistory

import os
os.environ["GOOGLE_API_KEY"] = "" # <--- PUT KEY HERE

# Chat model
llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash")

# Memory store
store = {}

def get_history(session_id="student"):
    if session_id not in store:
        store[session_id] = InMemoryChatMessageHistory()
    return store[session_id]

# Wrap with memory
learning = RunnableWithMessageHistory(
    llm,
    lambda session_id: get_history(session_id),
)

def tutor(topic):
    prompt = f"""
You are an AI Tutor. Teach the topic: {topic}
Steps:
1. Explain in simple steps
2. Real-world example
3. 3 MCQ questions
4. Ask student to answer
"""
    return learning.invoke(
        [HumanMessage(prompt)],
        config={"configurable": {"session_id": "student"}}
    ).content

def evaluate_answers(student_answers):
    prompt = f"""
Student answered: {student_answers}
1. Correct answers
2. Score /3
3. Explain mistakes
4. Suggest tips
"""
    return learning.invoke(
        [HumanMessage(prompt)],
        config={"configurable": {"session_id": "student"}}
    ).content

print(tutor("decision trees in machine learning"))
ans = input("Enter your MCQ answers: ")
print(evaluate_answers(ans))