# -*- coding: utf-8 -*-
"""Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MgvQcz3nXJvYBUVAKGRcyrEdTBC4ljqn
"""

pip install langchain-google-genai

import os
from getpass import getpass

if "GOOGLE_GEMINI_API" not in os.environ:
    os.environ["GOOGLE_GEMINI_API"] = getpass("please enter the google gemini apikey")

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model = "Gemini-2.5-pro",
    temperature = 0.7
)

from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain

prompt = PromptTemplate(
    input_variables = ["technology"],
    template = "Explain {tehnology} in simple terms"
)

chain = LLMChain(prompt = prompt, llm = llm)

responce = chain.run("Explain what is AI?")
print(responce)

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage

llm_vison = ChatGoogleGenerativeAI(model = "google-2.0-flash")

message = HumanMessage(content = [
    "text":"text", "text"="Describe what is in the image",
    "text":"image_url", "image_url" = ""
])

responce = llm_vison.generate([message])
print(responce)