# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JPpJRn73pecJ2nQGrscdEBbEv1mcNM9k
"""

pip install datasets

from datasets import load_dataset

# Load dataset (this may take a while for full download, so you can start with streaming)
ds = load_dataset("smolagents/android-control", split="train", streaming=True)

# Peek at a few samples
for i, example in enumerate(ds.take(2)):
    print(example.keys())
    print(example)