# -*- coding: utf-8 -*-
"""Url_classify_SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQnY0Q0-LciefZf4hvm3wDdd6fTkPxRK
"""

!pip install scikit-learn numpy pandas

import pandas as pd
import numpy as np
import re
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

data = pd.read_csv("/content/malicious_phish.csv")

data.head()

def clean_url(url):
    url = url.lower()  # Convert to lowercase
    url = re.sub(r'http[s]?://', '', url)  # Remove http/https
    url = re.sub(r'www\.', '', url)  # Remove www
    url = re.sub(r'[^a-z0-9]', ' ', url)  # Replace non-alphanumeric characters with spaces
    return url

url_data = data.copy() # Initialize url_data
url_data['cleaned_url'] = url_data['url'].apply(clean_url) # Correct the column name to 'url'

url_data['url_length'] = url_data['cleaned_url'].apply(len)

url_data['url_tokens'] = url_data['cleaned_url'].apply(lambda x: len(x.split()))

keywords = ['login', 'admin', 'secure', 'password', 'account', 'authentication']

def check_keywords(url, keywords):
    return sum([1 for keyword in keywords if keyword in url])

url_data['suspicious_keywords'] = url_data['cleaned_url'].apply(lambda x: check_keywords(x, keywords))

# Check the first few rows of the data to see the extracted features
display(url_data.head()) # Use display for better formatting

